---
- name: install apache
  yum: name=httpd update_cache=yes state=latest

- name: apache listen on port 8080
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state=present
    
- name: restart apache
  service: name=httpd state=restarted
