---
- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path: /etc/ssl/keys/localhost
    state: directory

- name: Generate self signed SSL certificates
  command: >
    openssl req
      -new
      -newkey rsa:4096
      -days 365
      -nodes
      -x509
      -subj "/C=US/ST=NY/L=NY/O=NA/CN=localhost"
      -keyout /etc/ssl/keys/localhost/localhost.key
      -out /etc/ssl/keys/localhost/localhost.cer
  args:
    creates: '/etc/ssl/keys/localhost.pem'

- name: Copy custom nginx.conf file 
  become: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx2.conf
    mode: 0644

- name: update ssl certificate in Nginx 
  become: yes
  replace: 
    path: /etc/nginx/nginx2.conf
    regexp: '{SSL_CERT}'
    replace: '/etc/ssl/keys/localhost/localhost.cer'
    backup: yes

- name: update ssl certificate key in Nginx 
  become: yes
  replace: 
    path: /etc/nginx/nginx2.conf
    regexp: '{SSL_CERT_KEY}'
    replace: '/etc/ssl/keys/localhost/localhost.key'
    backup: yes

