---
- name: Install prerequsities (epel repo)
  become: yes
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: disable selinux for nginx ssl
  become: yes
  selinux:
    state: disabled

- name: Install the nginx package
  become: yes
  yum:
   name: nginx
   state: present
  
- name: Create web root directory
  become: yes
  file:
    path: /var/www/html
    state: directory
    mode: 0755
    recurse: yes
 
- name: Copy custom index.html file 
  become: yes
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: 0644
 
- name: Edit Configuration in Nginx 
  become: yes
  replace: 
    path: /etc/nginx/nginx.conf
    regexp: 'root         /usr/share/nginx/html;'
    replace: 'root         /var/www/html/;'
    backup: yes

- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path: /etc/ssl/keys/localhost
    state: directory

- name: Generate self signed SSL certificates
  command: >
    openssl req
      -new
      -newkey rsa:4096
      -days 365
      -nodes
      -x509
      -subj "/C=US/ST=NY/L=NY/O=NA/CN=localhost"
      -keyout /etc/ssl/keys/localhost/test.darkmeter.ae.key
      -out /etc/ssl/keys/localhost/test.darkmeter.ae.crt
  args:
    creates: '/etc/ssl/keys/test.darkmeter.ae.pem'

- name: Copy custom nginx.conf file 
  become: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: update ssl certificate in Nginx 
  become: yes
  replace: 
    path: /etc/nginx/nginx.conf
    regexp: '{SSL_CERT}'
    replace: '/etc/ssl/keys/localhost/test.darkmeter.ae.crt'
    backup: yes

- name: update ssl certificate key in Nginx 
  become: yes
  replace: 
    path: /etc/nginx/nginx.conf
    regexp: '{SSL_CERT_KEY}'
    replace: '/etc/ssl/keys/localhost/test.darkmeter.ae.key'
    backup: yes

- name: start the nginx service
  become: yes
  systemd: 
    name: nginx 
    state: started 
    enabled: yes
